version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gutenberg_net

  mongo:
    image: mongo
    container_name: Gutenberg_Mongo
    restart: always
    command: mongod --port 27019
    ports:
      - 27019:27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - gutenberg_net

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8082
    environment:
      ME_CONFIG_MONGODB_PORT: 27019
      ME_CONFIG_MONGODB_SERVER: Gutenberg_Mongo
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27019/
    networks:
      - gutenberg_net
    depends_on:
      - mongo
networks:
  gutenberg_net:

volumes:
  redis_data:

